package main

import "sync"

type ProductTypesContainer struct {
	Mute         sync.Mutex
	ProductTypes []ProductType `json:"productType"`
}

type ProductType struct {
	ID                 string           `json:"id"`
	ProductTypeGroup   ProductTypeGroup `json:"productTypeGroup"`
	Name               string           `json:"name"`
	AttributeTypeId1   string           `json:"attributeTypeId1"`
	AttributeTypeName1 string           `json:"attributeTypeName1"`
	AttributeTypeId2   string           `json:"attributeTypeId2"`
	AttributeTypeName2 string           `json:"attributeTypeName2"`
	AttributeTypeId3   string           `json:"attributeTypeId3"`
	AttributeTypeName3 string           `json:"attributeTypeName3"`
	AttributeTypeId4   string           `json:"attributeTypeId4"`
	AttributeTypeName4 string           `json:"attributeTypeName4"`
	AttributeTypeId5   string           `json:"attributeTypeId5"`
	AttributeTypeName5 string           `json:"attributeTypeName5"`
	AttributeType      []AttributeType  `json:"attributeType"`
}

type AttributeType struct {
	ID            string        `json:"id"`
	Name          string        `json:"name"`
	Rank          string        `json:"rank"`
	Type          string        `json:"type"`
	AttributeUnit AttributeUnit `json:"attributeUnit"`
	GroupID       string        `json:"groupId"`
	GroupName     string        `json:"groupName"`
}

type AttributeUnit struct {
	ID         string `json:"id"`
	BaseUnitID string `json:"baseUnitId"`
	MulFactor  int64  `json:"mulFactor"`
	DivFactor  int64  `json:"divFactor"`
}

type ProductTypeGroup struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Generated by https://quicktype.io

type ProductsContainer struct {
	Product []Product `json:"product"`
}

type Product struct {
	Puid                        string             `json:"puid"`
	Ean                         string             `json:"ean"`
	ManufacturerSKU             string             `json:"manufacturerSKU"`
	IcecatID                    string             `json:"icecatId"`
	CnetID                      string             `json:"cnetId"`
	BechlemID                   string             `json:"bechlemId"`
	EClass                      string             `json:"eClass"`
	ManufacturerID              string             `json:"manufacturerId"`
	ManufacturerName            string             `json:"manufacturerName"`
	ProductNameWithManufacturer string             `json:"productNameWithManufacturer"`
	ShortDescription            string             `json:"shortDescription"`
	LongDescription             string             `json:"longDescription"`
	ProductTypeID               string             `json:"productTypeId"`
	ProductTypeGroupID          string             `json:"productTypeGroupId"`
	ProductTypeGroupName        string             `json:"productTypeGroupName"`
	ProductTypeName             string             `json:"productTypeName"`
	AttributeTypeId1            string             `json:"attributeTypeId1"`
	AttributeTypeName1          string             `json:"attributeTypeName1"`
	AttributeTypeId2            string             `json:"attributeTypeId2"`
	AttributeTypeName2          string             `json:"attributeTypeName2"`
	AttributeTypeId3            string             `json:"attributeTypeId3"`
	AttributeTypeName3          string             `json:"attributeTypeName3"`
	AttributeTypeId4            string             `json:"attributeTypeId4"`
	AttributeTypeName4          string             `json:"attributeTypeName4"`
	AttributeTypeId5            string             `json:"attributeTypeId5"`
	AttributeTypeName5          string             `json:"attributeTypeName5"`
	AttributeValue1             string             `json:"attributeValue1"`
	AttributeValue2             string             `json:"attributeValue2"`
	AttributeValue3             string             `json:"attributeValue3"`
	AttributeValue4             string             `json:"attributeValue4"`
	AttributeValue5             string             `json:"attributeValue5"`
	ProductSubTypeID            string             `json:"productSubTypeId"`
	ProductSubType              string             `json:"productSubType"`
	ProductLineID               string             `json:"productLineId"`
	ProductLine                 string             `json:"productLine"`
	ProductModel                string             `json:"productModel"`
	EstimateGrossWeight         string             `json:"estimateGrossWeight"`
	GrossDimX                   string             `json:"grossDimX"`
	GrossDimY                   string             `json:"grossDimY"`
	GrossDimZ                   string             `json:"grossDimZ"`
	CustomsTariffNumber         string             `json:"customsTariffNumber"`
	Deeplink                    string             `json:"deeplink"`
	StandardHTMLDatasheet       string             `json:"standardHtmlDatasheet"`
	StandardPDFDatasheet        string             `json:"standardPdfDatasheet"`
	ManufacturerSite            string             `json:"manufacturerSite"`
	ManufacturerDatasheet       string             `json:"manufacturerDatasheet"`
	ImageThumb                  string             `json:"imageThumb"`
	ImageThumbWidth             string             `json:"imageThumbWidth"`
	ImageThumbHeight            string             `json:"imageThumbHeight"`
	Image1                      string             `json:"image1"`
	ImageWidth1                 string             `json:"imageWidth1"`
	ImageHeight1                string             `json:"imageHeight1"`
	Image2                      string             `json:"image2"`
	ImageWidth2                 string             `json:"imageWidth2"`
	ImageHeight2                string             `json:"imageHeight2"`
	Image3                      string             `json:"image3"`
	ImageWidth3                 string             `json:"imageWidth3"`
	ImageHeight3                string             `json:"imageHeight3"`
	Image4                      string             `json:"image4"`
	ImageWidth4                 string             `json:"imageWidth4"`
	ImageHeight4                string             `json:"imageHeight4"`
	Image5                      string             `json:"image5"`
	ImageWidth5                 string             `json:"imageWidth5"`
	ImageHeight5                string             `json:"imageHeight5"`
	EnergyLabel                 string             `json:"energyLabel"`
	EntryDate                   string             `json:"entryDate"`
	Rank                        string             `json:"rank"`
	Qualification               string             `json:"qualification"`
	WarrantyText                string             `json:"warrantyText"`
	MarketingText               string             `json:"marketingText"`
	HTMLSpecs                   string             `json:"htmlSpecs"`
	RecommendedRetailPriceNet   string             `json:"recommendedRetailPriceNet"`
	Price                       string             `json:"price"`
	PriceCalc                   string             `json:"priceCalc"`
	CurrencyCode                string             `json:"currencyCode"`
	PriceCalcVat                string             `json:"priceCalcVat"`
	PriceLastUpdate             string             `json:"priceLastUpdate"`
	PriceSupplierID             string             `json:"priceSupplierId"`
	PriceSupplierName           string             `json:"priceSupplierName"`
	PriceSupplierItemID         string             `json:"priceSupplierItemId"`
	PriceSupplierSKU            string             `json:"priceSupplierSKU"`
	StockSupplierText           string             `json:"stockSupplierText"`
	StockStatus                 string             `json:"stockStatus"`
	StockStatusText             string             `json:"stockStatusText"`
	Stock                       string             `json:"stock"`
	ExternalStock               string             `json:"externalStock"`
	IncomingStock               string             `json:"incomingStock"`
	StockAvailabilityDate       string             `json:"stockAvailabilityDate"`
	StockLastUpdate             string             `json:"stockLastUpdate"`
	AggregatedStatus            string             `json:"aggregatedStatus"`
	AggregatedStatusText        string             `json:"aggregatedStatusText"`
	AggregatedStock             string             `json:"aggregatedStock"`
	AggregatedSupplierItems     string             `json:"aggregatedSupplierItems"`
	SupplierItems               []SupplierItem     `json:"supplierItems"`
	Attributes                  []Attribute        `json:"attributes"`
	AttributeClusters           []AttributeCluster `json:"attributeClusters"`
	Accessories                 []Accessory        `json:"accessories"`
}

type Accessory struct {
	ReferencedProductID string `json:"referencedProductId"`
	TypeID              string `json:"typeId"`
	Type                string `json:"type"`
}

type Attribute struct {
	DisplayValue           string `json:"displayValue"`
	AttributeTypeID        int64  `json:"attributeTypeId"`
	AttributeTypeName      string `json:"attributeTypeName"`
	AttributeTypeRank      int64  `json:"attributeTypeRank"`
	AttributeTypeGroupID   int64  `json:"attributeTypeGroupId"`
	AttributeTypeGroupName string `json:"attributeTypeGroupName"`
}

type AttributeCluster struct {
	ID                     int64  `json:"id"`
	ProductTypeID          int64  `json:"productTypeId"`
	ProductTypeName        string `json:"productTypeName"`
	AttributeTypeName      string `json:"attributeTypeName"`
	AttributeTypeGroupName string `json:"attributeTypeGroupName"`
	Name                   string `json:"name"`
	Rank                   int64  `json:"rank"`
}

type SupplierItem struct {
	ID                        string    `json:"id"`
	Ean                       string    `json:"ean"`
	ManufacturerSKU           string    `json:"manufacturerSKU"`
	SupplierSKU               string    `json:"supplierSKU"`
	SupplierID                string    `json:"supplierId"`
	SupplierName              string    `json:"supplierName"`
	ManufacturerName          string    `json:"manufacturerName"`
	ProductName               string    `json:"productName"`
	LongDescription           string    `json:"longDescription"`
	ConditionID               string    `json:"conditionId"`
	ConditionName             string    `json:"conditionName"`
	EOLProduct                string    `json:"eolProduct"`
	MatchQuality              string    `json:"matchQuality"`
	EanValid                  string    `json:"eanValid"`
	SpecialOffer              string    `json:"specialOffer"`
	Promotion                 string    `json:"promotion"`
	Vat                       string    `json:"vat"`
	CopyrightLevy             string    `json:"copyrightLevy"`
	CustomsTariffNumber       string    `json:"customsTariffNumber"`
	CountryOfOrigin           string    `json:"countryOfOrigin"`
	GrossDimX                 string    `json:"grossDimX"`
	GrossDimY                 string    `json:"grossDimY"`
	GrossDimZ                 string    `json:"grossDimZ"`
	WarrantyText              string    `json:"warrantyText"`
	Deeplink                  string    `json:"deeplink"`
	RecommendedRetailPriceNet string    `json:"recommendedRetailPriceNet"`
	Price                     string    `json:"price"`
	PriceCalc                 string    `json:"priceCalc"`
	CurrencyCode              string    `json:"currencyCode"`
	PriceCalcVat              string    `json:"priceCalcVat"`
	PriceLastUpdate           string    `json:"priceLastUpdate"`
	StockSupplierText         string    `json:"stockSupplierText"`
	StockStatus               string    `json:"stockStatus"`
	StockStatusText           string    `json:"stockStatusText"`
	Stock                     string    `json:"stock"`
	ExternalStock             string    `json:"externalStock"`
	IncomingStock             string    `json:"incomingStock"`
	StockAvailabilityDate     string    `json:"stockAvailabilityDate"`
	LastStockUpdate           string    `json:"lastStockUpdate"`
	Project                   []Project `json:"project"`
}

type Project struct {
	SupplierProjectID     string `json:"supplierProjectId"`
	ManufacturerProjectID string `json:"manufacturerProjectId"`
	ProjectName           string `json:"projectName"`
	EndCustomer           string `json:"endCustomer"`
	Price                 int64  `json:"price"`
	ValidFrom             string `json:"validFrom"`
	ValidTo               string `json:"validTo"`
	TargetQuantity        int64  `json:"targetQuantity"`
	RemainingQuantity     int64  `json:"remainingQuantity"`
	MinQuantity           int64  `json:"minQuantity"`
	ProjectLastUpdate     string `json:"projectLastUpdate"`
}
